export const CHECK_EXISTING_USER = 'CHECK_EXISTING_USER';
export const SET_EXISTING_USER = 'SET_EXISTING_USER';
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const SET_NEW_USER = 'SET_NEW_USER';
export const SIGN_UP_USER = 'SIGN_UP_USER';
